### ISSUE TITLE
Migrate away from Travis CI

### ISSUE THREAD

**Issue by johnthagen** [johnthagen/min-sized-rust#23]
Since Travis CI is no longer free for FOSS projects, need to migrate this CI to something else, likely GitHub Actions.

**Comment by johnthagen** [comment]
Current status of remaining free Travis credits:

> 9220 available credits (purchase date: January 03, 2021)
> You have used 780 of 10000 credits

**Comment by MrTact** [comment]
Circle CI’s free plan grants 2500 credits/week.

TK

On January 3, 2021, XAMPPRocky <notifications@github.com> wrote:
> Current status of remaining free Travis credits:
>
> > 9220 available credits (purchase date: January 03, 2021)
> >  You have used 780 of 10000 credits
> >
>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/johnthagen/min-sized-rust/issues/23#issuecomment-
753655528>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAKVO2N3ODPIHYGKYT3HYSTSYCXSDANCNFSM4VSCA3BA>.
