### ISSUE TITLE
Resulting executable sizes are not reported consistently

### ISSUE THREAD

**Issue by vi** [johnthagen/min-sized-rust#6]
> On macOS, the final binary size is reduced to 51KB.

> On macOS, the final binary size is reduced to 30KB.

I think each section (including "baseline, before optimisation") should have a demo project with target file size available. The size may even be in section title.

**Comment by johnthagen** [comment]
Since the actual size reductions will vary widely per project, I'm focusing the goals of `min-sized-rust` to simply document *how* to perform all of the size reducing techniques available rather than a detailed size output for a particular project, especially since the ones in this project are basically just "Hello, World" and are not very representative.
