### ISSUE TITLE
Ideas to enhance the project

### ISSUE THREAD

**Issue by vi** [johnthagen/min-sized-rust#7]
1. Use (or add) less trivial example, with some external dependencies. For example, opening a file, calculating md5summ, outputting it in hex.
2. Include not just target size for MacOS, but a table of sizes across major platforms.

**Comment by johnthagen** [comment]
I think 1. should be reserved for another blog post. I'd like to keep this repository just a reference guide about *what* steps a user can take to reduce binary size rather than an in depth study. But if such a blog post were written, I'd happily link it in the References section of the README.

**Comment by johnthagen** [comment]
Since the actual size reductions will vary widely per project, I'm focusing the goals of `min-sized-rust` to simply document *how* to perform all of the size reducing techniques available rather than a detailed size output for a particular project, especially since the ones in this project are basically just "Hello, World" and are not very representative.
